spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/intern_intelligence
    password: 2810
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml

tmdb:
  url: https://api.themoviedb.org/3
  api-key: 4dfaefed514914add78d122b66879082
  default-language: en-US


