spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/intern_intelligence
    password: 2810
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml